### ISSUE TITLE
Can't find samples/sample.kimi

### ISSUE THREAD

**Issue by kkoci** [vakila/kimi#9]
Hi, I was just trying to run kimi on my pc, but reading the README.md it mentions a:

`samples/sample.kimi`

Can't find it, Am I missing something?

I'm also researching on new languages and how to build one

Thanks in advance!

**Comment by mschmo** [comment]
Make sure you pulled the entire repo. `samples/sample.kiwi` is located here: https://github.com/vakila/kimi/blob/master/samples/sample.kimi

**Comment by kkoci** [comment]
Awesome!

Weird thing though, well whatever, Thank You very much
